### ISSUE TITLE
WoodenBucket: Things that need work!

### ISSUE THREAD

**Issue by Thepiggy** [BuiltBrokenModding/SingleBlockMods#1] opened 2015-08-07 04:14 UTC
So if you pick up some liquids (<EnderIO:bucketNutrient_distillation> and some others) it turns the bucket into a normal iron bucket full of the Nutrient distillation, and just some normal picking up and placing of the liquids, IE: water and lava don't update when placed, you can't have the bucket break grass if clicked on with a wb water bucket (normal iron buckets do that) little stuff, but the big issue is the buckets turning into iron buckets thing, that's a game breaker for my mod pack.

**Comment by DarkGuardsman** [comment] 2015-08-07 18:29
The wooden buckets turning into iron buckets might actually be caused by another mod. There is an event system that both my buckets and vanilla uses. When missused by a mod it can return the wrong bucket type. Too fix this I might just remove the event call which honestly shouldn't cause any issues. 

As for the block updates it is being worked on and should be fixed next update on curse.

**Comment by DarkGuardsman** [comment] 2015-08-07 23:57
Added a patch that should fix the Iron bucket issue https://github.com/BuiltBrokenModding/SingleBlockMods/commit/e2df91742f430ffb23307b917f5197505387ec9a
Also reported the issue to EnderIO as that will effect other mods
https://github.com/SleepyTrousers/EnderIO/issues/2703

**Comment by DarkGuardsman** [comment] 2015-08-08 01:31
Fixed water and lava placement not updating. Looks like it was a block ID issue where MC has two separate fluid blocks for each fluid. One will flow the other will do nothing. 

https://github.com/BuiltBrokenModding/SingleBlockMods/commit/833339be3c495a5691d2698ce88f4f1073014280

**Comment by DarkGuardsman** [comment] 2015-08-08 01:45
Fixed buckets not replacing blocks such as grass https://github.com/BuiltBrokenModding/SingleBlockMods/commit/16aa87ef231871acffb707bb10bc4008fe06856b

**Closed by DarkGuardsman** 2015-08-08 01:45 UTC
Labels: bug
